name: CI Pipeline

on:
  push:
    paths:
      - 'code/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with:
          path: 'code'

      - name: Set up Python
        working-directory: ./code
        run: |
          echo 'export PYENV_VERSION=3.11.9' >> $GITHUB_ENV
          pyenv global 3.11.9
          pip --version

      - name: Build API
        working-directory: ./code
        run: make build

      - name: Run tests
        working-directory: ./code
        run: make test

      - name: Perform code linting
        working-directory: ./code
        run: make lint

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin docker.io

      - name: Build and push Docker image
        working-directory: ./code
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/cipipelinewithgithubactions:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/cipipelinewithgithubactions:latest
