name: CI Pipeline

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'Makefile'
      - 'requirements.txt'
      - 'Dockerfile'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v4
        with:
          path: 'code'
          clean: true  # Important for self-hosted runners

      - name: Verify changed files
        run: |
          echo "Changed files:"
          git diff --name-only HEAD^ HEAD || echo "Initial commit - showing all files"
          echo "Current files:"
          ls -R

      - name: Set up Python
        working-directory: ./code
        run: |
          echo 'export PYENV_VERSION=3.11.9' >> $GITHUB_ENV
          pyenv global 3.11.9
          pip install -r requirements.txt

      - name: Build API
        working-directory: ./code
        run: make build

      - name: Run tests
        working-directory: ./code
        run: make test

      - name: Perform code linting
        working-directory: ./code
        run: make lint

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin docker.io

      - name: Build and push Docker image
        working-directory: ./code
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/cipipelinewithgithubactions:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/cipipelinewithgithubactions:latest
