name: CI Pipeline

on:
  push:
    paths:
      - 'code/**'
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-push:
    runs-on: self-hosted # Uses your self-hosted runner
    
    steps:
  - uses: actions/checkout@v4

  - name: Set up Python
    run: |
      echo 'export PYENV_VERSION=3.11.9' >> $GITHUB_ENV  # Use a known working version
      pyenv global 3.11.9
      pip --version  # Verify pip is available

  - name: Build
    run: make build  # Now pip will work!

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build API
      run: make build

    - name: Run tests
      run: make test

    - name: Perform code linting
      run: make lint

    - name: Login to Docker Registry
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin ${{ secrets.DOCKER_REGISTRY }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_REGISTRY }}/your-image-name:latest .
        docker push ${{ secrets.DOCKER_REGISTRY }}/your-image-name:latest
